spring.application.name=backend

# =========================
# MySQL Database
# =========================
spring.datasource.url=jdbc:mysql://localhost:3306/srishticonnect_db
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# =========================
# JPA / Hibernate
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# =========================
# Server
# =========================
server.port=8080


# =========================
# JWT Configuration
# =========================
jwt.secret=SrishtiConnectSecretKeyForJWTAuthentication2026SecureKey123456789
jwt.expiration=86400000


# =========================
# Google OAuth2
# =========================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# Google redirects here after successful authentication
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}